### PR TITLE
Handling `archiveless` posts in REST API queries

### LINKED ISSUE #61: Handling `archiveless` posts in REST API queries
### Description

I think there is a reasonable expectation that this plugin would not impact the site's admin, where editors would need access to all posts, archived or not.

This doesn't happen automatically. It's currently the responsibility of site admins to fix regressions, a feature?, added by the Archiveless plugin.

Take the [Page Attributes](https://make.wordpress.org/support/user-manual/pages/page-attributes/) feature as an example. This plugin removes the _archived_ pages from that list since the REST API query performed is the default query with params.

The same is true for the other parts of the WordPress back-end, like page lists and dropdowns, quick and bulk edits, etc.

---

One problem we have here is that there needs to be more context about where the REST API request comes from. We can confirm the user's capability, but not that the request is coming from a Slotfill for the Page Attributes in a specific post type.

The REST API, however, provides a `context` param.

> The `edit` context is used to make the response include the fields needed to edit the resource. So, the edit context is always used when doing GET requests to obtain the data for editing.

[Source](https://make.xwp.co/2017/07/25/defining-context-in-the-wp-rest-api/).

That means we can reasonably assume that REST API requests using the `edit` context, in the back-end or front-end of the site, are being performed for editing purposes, where we want to show the archived posts.

Here is some pseudocode of what I'm suggesting.

```php
/**
 * Filter the query to include `archiveless` posts.
 *
 * @param array           $args    Array of arguments for WP_Query.
 * @param WP_REST_Request $request The REST API request.
 * @return array
 */
function filter_query_parent_posts( $args, $request ): array {
	// Check the edit context from WP_REST_Request.
	if ( 'edit' !== $request->get_param( 'context' ) ) {
		return $args;
	}

	$args['include_archiveless'] = true;

	return $args;
}
add_filter( 'rest_page_query', 'filter_query_parent_posts', 10, 2 );
```

### Use Case

This bug recently affected a [client site](https://l.alley.dev/0598d7000a). The client has a post type where they can't select the parent post in the Page Attributes slotfill because the archived parent doesn't appear in the results list.

### PR DESCRIPTION
**Pull request by renatonascalves**
- Filters to all post types with REST support;
- Filter the REST API query with the edit context to include `archiveless` posts.

fixes #61

### CODE REVIEW

File: inc/class-archiveless.php [hunk 1]
```diff
@@ -224,15 +224,46 @@ public function updated_post_meta( $meta_id, $object_id, $meta_key, $meta_value
 	}
 
 	/**
-	 * Add a filter to all post types for REST response modification.
+	 * Filters to all post types with REST support.
```
Comment (attackant) [inline inc/class-archiveless.php:227]: Maybe should read "Add filters..."

File: inc/class-archiveless.php [hunk 2]
```diff
@@ -224,15 +224,46 @@ public function updated_post_meta( $meta_id, $object_id, $meta_key, $meta_value
...
+	 * @param array           $args    Array of arguments for WP_Query.
+	 * @param WP_REST_Request $request The REST API request.
+	 * @return array
 	 */
-	public function filter_rest_response() {
-		// Override the post status in the REST response to avoid Gutenbugs.
-		foreach ( get_post_types() as $allowed_post_type ) {
-			add_filter( 'rest_prepare_' . $allowed_post_type, [ $this, 'rest_prepare_post_data' ] );
+	function filter__rest_post_type_query( $args, $request ): array {
+		/**
```
Comment (attackant) [inline inc/class-archiveless.php:248]: Should this be `public`?

**Review by attackant — APPROVED** [review]
Couple suggestions, no blockers 🐙
